# Generated by Django 4.0.1 on 2022-01-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ogrenci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50)),
                ('soyad', models.CharField(max_length=50)),
                ('bolum', models.CharField(max_length=50)),
                ('tckn', models.CharField(max_length=50)),
                ('vize', models.FloatField(max_length=50)),
                ('final', models.FloatField(max_length=50)),
                ('ortalama', models.FloatField(max_length=50)),
                ('harfnotu', models.CharField(max_length=50)),
            ],
        ),
    ]
