# Generated by Django 4.0.1 on 2022-01-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ogrenci',
            name='id',
        ),
        migrations.AlterField(
            model_name='ogrenci',
            name='tckn',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
